branches:
  only:
    - develop
    
environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"
  dotnetcore_version: 2.1.302
  nodejs_version: "8"

install:
  - cmd: SET PATH=%PYTHON%;%PYTHON%\Scripts;%JAVA_HOME%\bin;%PATH%
  - cmd: copy "C:\Program Files (x86)\Apache\Maven\bin\mvn.cmd" "C:\Program Files (x86)\Apache\Maven\bin\mvn.bat"

build_script:
  - ps: |
      $base = pwd;
      # Download Functions Core Tools
      Remove-Item -Force "$base\Azure.Functions.Cli.zip" -ErrorAction Ignore
      Remove-Item -Recurse -Force "$base\Azure.Functions.Cli" -ErrorAction Ignore
      Write-Output "Downloading Functions Host...."
      $url = "https://functionsclibuilds.blob.core.windows.net/builds/2/latest/Azure.Functions.Cli.win-x64.zip"
      $output = "$base\Azure.Functions.Cli.zip"
      $wc = New-Object System.Net.WebClient
      $wc.DownloadFile($url, $output)
      Expand-Archive "$base\Azure.Functions.Cli.zip" -DestinationPath "$base\Azure.Functions.Cli"
      $Env:Path = $Env:Path+";$base\Azure.Functions.Cli"

      # Clone and install function maven plguin and archetype
      $functionPom = [xml](gc ".\azure-functions-maven-plugin\pom.xml")
      $functionVersion = $functionPom.project.version
      Write-Output "Function maven plugin version: $functionVersion"
      mvn clean install

      # Generate function project through archetype
      Remove-Item -Recurse -Force ".\e2etestproject" -ErrorAction Ignore
      mkdir e2etestproject
      cd e2etestproject
      mvn archetype:generate -DarchetypeGroupId="com.microsoft.azure" -DarchetypeArtifactId="azure-functions-archetype" -DgroupId="com.microsoft" -DartifactId="e2etestproject" -Dversion="1.0-SNAPSHOT" -Dpackage="com.microsoft" -DappRegion="westus" -DresourceGroup="e2etest-java-functions-group" -DappName="e2etest-java-functions" -B
      # Update e2e project pom to use the latest maven plugin
      $e2ePomFile = gi ".\e2etestproject\pom.xml"
      $e2ePom = [xml](gc $e2ePomFile)
      $e2ePom.project.properties.'azure.functions.maven.plugin.version'=$functionVersion
      $e2ePom.Save($e2ePomFile.Fullname)
      mvn -f ".\e2etestproject\pom.xml" clean package
      cd ..

      # Run function host
      $Env:FUNCTIONS_WORKER_RUNTIME = "java"
      $Env:AZURE_FUNCTIONS_ENVIRONMENT = "development"
      $Env:AzureWebJobsScriptRoot = "$base\e2etestproject\e2etestproject\target\azure-functions\e2etest-java-functions"
      $proc = start-process -filepath "$base\Azure.Functions.Cli\func.exe" -WorkingDirectory "$Env:AzureWebJobsScriptRoot" -ArgumentList "host start" -RedirectStandardOutput "output.txt" -RedirectStandardError "error.txt" -PassThru
      Start-Sleep -s 30
      
test_script:
  - ps: |
      $response = curl http://localhost:7071/api/HttpTrigger-Java?name=CI
      $success = $response.Content -eq "Hello, CI"
      if (-not $success) { exit 1 } 

on_finish:
  - ps: | 
      Stop-Process -Id $proc.Id -Erroraction Ignore
      # Output standard input stream and error stream
      Write-Output "Standard input stream :" (gc ".\output.txt")
      Write-Output "Standard error stream :" (gc ".\error.txt")
