image:
  - Visual Studio 2015
  - Ubuntu

branches:
  only:
    - feature-spring

environment:
  JAVA_HOME: "C:\\Program Files\\Java\\jdk1.8.0"

install:
  - cmd: SET PATH=%JAVA_HOME%\bin;%PATH%

build_script:
  - cmd: git clone %SDK_REPO% && mvnw clean install -f azure-spring-cloud-sdk/resource-manager/v2019_05_01_preview/pom.xml && mvnw clean verify && mvnw cobertura:cobertura
  - sh: |
          git clone $SDK_REPO
          ./mvnw clean install -f azure-spring-cloud-sdk/resource-manager/v2019_05_01_preview/pom.xml
          ./mvnw clean verify
          ./mvnw cobertura:cobertura

on_success:
  - curl -s https://codecov.io/bash
