name: RichNavIndexing
on:
  pull_request:
  push:
    branches:
      - develop
      - validate/*

jobs:
  richnav:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: microsoft/RichCodeNavIndexer@c8b97bc908f7bc0151fe4872aa029e99b2a0b96b # v0.1
      with:
        languages: java
        repo-token: ${{ github.token }}
